### ISSUE TITLE
Plain cell mistaken for fragment in slideshow

### ISSUE THREAD

**Issue by fonnesbeck** [damianavila/live_reveal#30] opened 2014-08-02 16:12 UTC
When editing the slideshow cell types in `live_reveal`, several (but not all) cells specified as a plain cell (i.e. cell type blank) get interpreted as a fragment, and do not appear unless you press the spacebar. When the cells are first specified, it seems to work okay, but as you edit slides (particularly changing a cell above to be a "slide" or "sub-slide", the cells begin behaving as fragments.

[Here is a video demonstrating the behavior](http://d.pr/v/BYhf)

**Comment by damianavila** [comment] 2015-02-01 02:42
Just an update... I will test this again with master this week to see if I still can see the errors (since IPython/Jupyter changes a lot, and RISE make some changes accordingly, we have to check if the issues are still present).

**Comment by takluyver** [comment] 2015-02-12 01:07
I can reproduce this with IPython from current master.

**Comment by damianavila** [comment] 2015-02-13 13:55
OK, I will try to reproduce it too... and the go for a fix... :wink:

**Comment by takluyver** [comment] 2015-02-21 22:58
I think this should be fixed now that #65 is merged.

**Comment by damianavila** [comment] 2015-02-21 23:57
I agree... I can no longer reproduce the issue, so closing...
@fonnesbeck, please reopen it if you see the same behaviour again.

**Closed by damianavila** 2015-02-21 23:57 UTC
Labels: bug
